export const GET_ALL_CHARITIES_LOADING = 'GET_ALL_CHARITIES_LOADING';
export const GET_ALL_CHARITIES_SUCCESS = 'GET_ALL_CHARITIES_SUCCESS';
export const GET_ALL_CHARITIES_ERROR = 'GET_ALL_CHARITIES_ERROR';