export const FETCH_ALL_DONATIONS_LOADING = 'FETCH_ALL_DONATIONS_LOADING';
export const FETCH_ALL_DONATIONS_SUCCESS = 'FETCH_ALL_DONATIONS_SUCCESS';
export const FETCH_ALL_DONATIONS_ERROR = 'FETCH_ALL_DONATIONS_ERROR';

export const UPDATE_TOTAL_DONATE_LOADING = 'UPDATE_TOTAL_DONATE_LOADING';
export const UPDATE_TOTAL_DONATE_SUCCESS = 'UPDATE_TOTAL_DONATE_SUCCESS';
export const UPDATE_TOTAL_DONATE_ERROR = 'UPDATE_TOTAL_DONATE_ERROR';



