export const FETCH_ALL_DONATIONS_LOADING = 'FETCH_ALL_DONATIONS_LOADING';
export const FETCH_ALL_DONATIONS_SUCCESS = 'FETCH_ALL_DONATIONS_SUCCESS';
export const FETCH_ALL_DONATIONS_ERROR = 'FETCH_ALL_DONATIONS_ERROR';

export const MAKE_PAYMENT_LOADING = 'MAKE_PAYMENT_LOADING';
export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const MAKE_PAYMENT_ERROR = 'MAKE_PAYMENT_ERROR';



export const UPDATE_TOTAL_DONATE_LOADING = 'UPDATE_TOTAL_DONATE_LOADING';
export const UPDATE_TOTAL_DONATE_SUCCESS = 'UPDATE_TOTAL_DONATE_SUCCESS';
export const UPDATE_TOTAL_DONATE_ERROR = 'UPDATE_TOTAL_DONATE_ERROR';



